import React, { useState } from 'react';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '../components/Screen';
import { Card, PageHeader, SectionTitle, StatusBadge } from '../components/Primitives';
import { useMonitoring } from '../state/MonitoringContext';
import { colors, radius } from '../theme';
import { environment } from '../config/environment';

const menu = [
  ['Errors', 'warning-outline', 'Inspect HTTP failures'], ['Docker', 'logo-docker', 'Containers and actions'], ['Nginx', 'server-outline', 'Web-server performance'], ['Statistics', 'bar-chart-outline', 'Historical telemetry'], ['Alerts', 'notifications-outline', 'Notification history'], ['Remote Control', 'terminal-outline', 'Authorized API commands'], ['Settings', 'settings-outline', 'Connection and preferences'],
] as const;
export function MoreScreen({ navigation }: { navigation: any }) { const { alerts } = useMonitoring(); return <Screen><PageHeader eyebrow="COMMAND CENTER" title="More" /><Card style={styles.mode}><View><Text style={styles.modeTitle}>{environment.mode === 'mock' ? 'Mock API mode' : 'Production API mode'}</Text><Text style={styles.muted}>{environment.mode === 'mock' ? 'Simulated, clearly labeled telemetry' : 'Live monitoring API connection'}</Text></View><StatusBadge status={environment.mode === 'mock' ? 'warning' : 'online'} label={environment.mode.toUpperCase()} /></Card><SectionTitle title="Monitoring" /><Card style={styles.menu}>{menu.map(([name, icon, caption], index) => <Pressable key={name} onPress={() => navigation.navigate(name)} style={[styles.item, index > 0 && styles.border]}><View style={styles.itemIcon}><Ionicons name={icon} size={18} color={name === 'Alerts' && alerts.some(a => !a.read) ? colors.red : colors.blue} /></View><View style={styles.itemBody}><Text style={styles.itemTitle}>{name}</Text><Text style={styles.muted}>{caption}</Text></View>{name === 'Alerts' && alerts.some(a => !a.read) ? <View style={styles.count}><Text style={styles.countText}>{alerts.filter(a => !a.read).length}</Text></View> : null}<Ionicons name="chevron-forward" size={17} color={colors.subtle} /></Pressable>)}</Card></Screen>; }
export function SettingsScreen() { const [critical, setCritical] = useState(true); const [warnings, setWarnings] = useState(true); const [errors, setErrors] = useState(true); const [autoRefresh, setAutoRefresh] = useState(true); return <Screen><PageHeader eyebrow="PREFERENCES" title="Settings" /><SectionTitle title="Monitoring API" /><Card style={styles.settings}><Setting label="Connection" value={environment.mode === 'mock' ? 'Mock API · connected' : environment.apiBaseUrl} /><Setting label="API URL" value={environment.mode === 'mock' ? 'Set EXPO_PUBLIC_API_BASE_URL to connect' : environment.apiBaseUrl} /><Setting label="Authentication" value="Secure session storage ready" /><Setting label="Session" value="Not signed in" /></Card><SectionTitle title="Notifications" /><Card style={styles.settings}><Toggle label="Critical alerts" value={critical} setValue={setCritical} /><Toggle label="Error alerts" value={errors} setValue={setErrors} /><Toggle label="Warning alerts" value={warnings} setValue={setWarnings} /></Card><SectionTitle title="Refresh" /><Card style={styles.settings}><Toggle label="Automatic refresh" value={autoRefresh} setValue={setAutoRefresh} /><Setting label="Interval" value={autoRefresh ? '30 seconds' : 'Manual'} /></Card><SectionTitle title="About" /><Card style={styles.settings}><Setting label="Theme" value="Dark (system ready)" /><Setting label="Version" value="1.0.0" /><Setting label="Build" value="Mobile monitoring client" /></Card></Screen>; }
function Setting({ label, value }: { label: string; value: string }) { return <View style={styles.setting}><Text style={styles.settingLabel}>{label}</Text><Text style={styles.settingValue} numberOfLines={2}>{value}</Text></View>; }
function Toggle({ label, value, setValue }: { label: string; value: boolean; setValue: (value: boolean) => void }) { return <View style={styles.setting}><Text style={styles.settingLabel}>{label}</Text><Switch value={value} onValueChange={setValue} trackColor={{ false: colors.subtle, true: '#238636' }} thumbColor={colors.text} /></View>; }
const styles = StyleSheet.create({ mode: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, modeTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, muted: { color: colors.muted, fontSize: 11, marginTop: 3 }, menu: { paddingVertical: 0 }, item: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10 }, border: { borderTopWidth: 1, borderTopColor: colors.border }, itemIcon: { width: 30, height: 30, borderRadius: radius.sm, backgroundColor: '#58a6ff12', alignItems: 'center', justifyContent: 'center' }, itemBody: { flex: 1 }, itemTitle: { color: colors.text, fontWeight: '700', fontSize: 14 }, count: { backgroundColor: colors.red, minWidth: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, countText: { color: colors.text, fontSize: 10, fontWeight: '800' }, settings: { paddingVertical: 0 }, setting: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 20, borderBottomWidth: 1, borderBottomColor: colors.border }, settingLabel: { color: colors.text, fontSize: 13, fontWeight: '600', flex: 1 }, settingValue: { color: colors.muted, fontSize: 11, textAlign: 'right', flex: 1 } });
